### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Tskading** [Tskading/Game-Meme#9]
I was also wondering if front-end could come up with a color pallet for our page.  I REALLY love the header image - and I think we could build off of that color set.  Like a dark gray background, and some reds, oranges, and blues to highlight the remaining parts of the page.  Definitely a bonus type thing, but I do think it would really add some legitimacy to our page.  Let me know what you think!

**Comment by CoryKDev** [comment]
we will check out some ideas for that
